apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-redis.yml -o k8s
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: broker
  name: broker
  namespace: kafka-stack
spec:
  ports:
    - name: "29092"
      port: 29092
      targetPort: 29092
    - name: "29093"
      port: 29093
      targetPort: 29093
  selector:
    io.kompose.service: broker
