apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-redis.yml -o k8s
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: control-center
  name: control-center
  namespace: kafka-stack
spec:
  ports:
    - name: "9021"
      port: 9021
      targetPort: 9021
  selector:
    io.kompose.service: control-center
