apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-redis.yml -o k8s
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: redisinsight
  name: redisinsight
  namespace: kafka-stack
spec:
  ports:
    - name: "5540"
      port: 5540
      targetPort: 5540
  selector:
    io.kompose.service: redisinsight
