apiVersion: apps/v1
kind: Deployment
metadata:
  name: journal-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: journal-service
  template:
    metadata:
      labels:
        app: journal-service
    spec:
      containers:
        - name: journal-service
          image: journal-service:1.0
          ports:
            - containerPort: 8087
          livenessProbe:
            httpGet:
              path: /api/journal/actuator/health
              port: 8087
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/journal/actuator/health
              port: 8087
            initialDelaySeconds: 30
            periodSeconds: 10